# settings.yml for SearXNG
# Docs: https://docs.searxng.org/admin/settings/settings.html

use_default_settings: true

general:
  debug: true
  instance_name: "SearXNG Railway"

search:
  formats:
    - html
    - json
    - csv

server:
  # Will be picked up from SEARXNG_BASE_URL env in Docker
  base_url: !env BASE_URL
  secret_key: "my-custom-secret-key-from-env"
  limiter: false
  image_proxy: true
  port: !env PORT

ui:
  static_use_hash: true
  theme_args:
    simple_style: dark

# Optional Redis cache (uncomment if you enable REDIS_URL in Railway)
# redis:
#   url: !env REDIS_URL

engines:
  # --- Default engines are loaded via use_default_settings ---
  # Add custom ones below

  - name: webcrawlerapi
    engine: webcrawlerapi
    api_key: !env WEBCRAWLERAPI_KEY
    categories: general
    timeout: 5.0
    disabled: false

  - name: webcrawlerapi-images
    engine: webcrawlerapi_images
    api_key: !env WEBCRAWLERAPI_KEY
    categories: images
    timeout: 5.0
    disabled: false
