# ✅ All corrections applied.

use_default_settings: true

general:
  debug: true
  instance_name: "SearXNG Railway"

search:
  formats:
    - html
    - json
    - csv

server:
  base_url: !env BASE_URL
  secret_key: "my-custom-secret-key-from-env"
  limiter: false
  image_proxy: true
  port: !env PORT

ui:
  static_use_hash: true
  theme_args:
    simple_style: dark

# Optional Redis cache
# redis:
#   url: !env REDIS_URL

engines:
  webcrawlerapi:
    categories:
      - general
    api_key: !env WEBCRAWLERAPI_KEY
    timeout: 5.0
    disabled: false

  # Renamed to use a hyphen to avoid the engine loader bug
  webcrawlerapi-images:
    categories:
      - images
    api_key: !env WEBCRAWLERAPI_KEY
    timeout: 5.0
    disabled: false
