# searxng/settings.yml
use_default_settings: true

general:
  debug: true

search:
  formats: [html, json, csv]

server:
  secret_key: "my-custom-secret-key-from-env"
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true

# -------------------------
# Custom engines
# -------------------------
engines:
  - name: webcrawlerapi
    engine: webcrawlerapi            # <-- must match file name WITHOUT .py
    api_key: !env WEBCRAWLERAPI_KEY
    categories: general
    timeout: 5.0
    disabled: false

  - name: webcrawlerapi-images
    engine: webcrawlerapi_images     # <-- must match file name WITHOUT .py
    api_key: !env WEBCRAWLERAPI_KEY
    categories: images
    timeout: 5.0
    disabled: false
